// <auto-generated />
namespace OurDestination.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Month_Add_With_PaymentAmount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Month_Add_With_PaymentAmount));
        
        string IMigrationMetadata.Id
        {
            get { return "202003091748348_Month_Add_With_PaymentAmount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
